language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-item-service
  skip_cleanup: true
  api_key:
    secure: oY0gn6tW1UB4XK0thK3jfwzJovdz3y/PBR6OgxBzNqstjLU/vZkmYwsS9pJLcmCNVsD/4x8B3x66LT1ojdj56b+VmmzDqPYNIt+C9KqfColyfRnsKEip0GIg4wqWBUXLLPsMogRDepkkNZIRWt/i6603eFp3TLKkblZOf7YSMN/6frtIjv6TvlK72xCc7CbCjGcTrbgQjVjiY53YIBFC1SQVik5g3enJwmPGucqc3r4b/+1PQOl4+UXVutUTD/qVAU/Ygn29k+hOhv4OOQT/YkEZmwuKW+pHJNFvdUqNHF8iBNxkFW/2Az+cEaK+h5x5lAO2QAVPqIdL3pAzrCOE2zp0XydYxUepqSzi2xZR2y7wZKDD2nElpEdPZHcVbumuw+27Wmb9+Y/cl/6Sp1vx0Mbdd+7HAjxTuRJdPIXZPv6HjagUNS3haFNmX5eAJOQBEBTWShGie8tNwP0d8guFEQmEfQm9xE5B0D9LlupxXLUQKekDIbabGUat1rY3z64o4aYABF7iyUf39tYRonYtOND6ZZY009bdIzube1YiFB9fGeTbgOSH872vEmQzeQRybQUXnaHkJt9nAmnc8dyKpzCkV/ve5AqXow1coeOT44ggdmm55MiqqW5fgioXldQ7zF6Y6LHmyM0AUI6C0D2PWDNGyLjUg7T9SW/vdzUwYFw=
