language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-item-service
  skip_cleanup: true
  api_key:
    secure: 0GCD/4qgXhfqkrTZdlbGt0TCMXJ0cczBWnoaxnrDHK3y6eGXG0G+qBRH7WOHgobph6SlxXKpVm/TOxdmEXexXPsS9H/4/cTVmeFWu/I+j4bvssxtUaNlbG0Y4z+nRLOPkp3wCXTpqO3iXaI+TouWJ2gXGWM8xis9NTNo8a6uMJ9nxluF5jBPHeik3QIpSeW1ME44XDg6n7ARwrKMcfwD1DvHLOkPa6kO0Jus0gcbYXpjgiLnQOcjkZXkSa5GX4BHhdYq6WD4qiVPulMEQTpHq0i/QJScyWeY1+0+OweIW58m2sOm77EVLGAsahmr5SXAQ+wRSNu0E4PJnOMo4YCikvEwsZQ73vqUrYkMkPGlbPbCqo8swgFV7oQmEB+ezzClnNvwspHSXNYYxzFVOgBhYdsIY3/T0rFSLDq8MnIZrxlC+YzzyuUqRBlOs+3p2fdAPE1qi80oq7N3lTY8tvak5S472WgM/5fiTma8o5HY1RROPXfsWnd8q6CHQgKsqszcVdAltKmcAmbwAQFs6kwO7wY/i0X7hfCtqtx8dnaWsq1RjW6EiYBmVdJ0tMv0mU/6TOAtEwTNOBvDALxYXb3VVS6t6dxsnWF+gYIWF2AyfxjbMEreU8b43uA0QKmK5VWj9QcZGlri155C/YwCYUbSZvHRXUzD337YOe5FbZBPgag=
