language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-item-service
  skip_cleanup: true
  app_key:
    secure: nv7xOfeYZ/RFGfqMJpYprBi5pjzVx95HJpjX+I3mHPkgX7W6RqW4GnD4RC+oxctR45G2/w2xXLtWohuyF+l0Tx2euLItNA1eqJjSFOUmeexvjlNrayeGOBypLhDjjBK9hwxG4Myig/CNjB6krNuGqvax4flnkpRl/Gf0HqXZfCrJ/CrFHGDznxx9il4eq3hQwezgnxxzYCHT1D/NmEMjvdlg1YPo4vuOWJot7KQEv4AYkzFukdM/e/gSkJqBufBMd/KTRSnQXGZO7Ab0GFI2f1IeM6Pi9L1mqopadjffD/WRDM5eVLcz+JLcmdOIStcb5l+R5Aj3wW/P3fSihqpmmmDmcGWXnpwAR7EBbqsVGQiAKX26fM40nTJiBRj1az+XiVCB7MIbT++dd4PqFEB7Xg1iSAldA//2ZxRKvuFirWuxf6P5KdsHLXreffBvb/XF7mJzLgiam2WvHLpdeLWCRvTcZUUXyCwJ4JmVnT4yNmAjb8Dar/cQHKYsa8eZb1UrOey6URrWiNlH+2NJ4PXy90IplTveR9PEj4TyG3UAUHEfWHrAEONNoBsYftDRbdWp7BJhuQpLuXLk4DCpN0jNcUC7xsnPkxXc52HXII2zPBqWpVpcfgZIwrr/K4j0jYjlomDhFgtyyCgpFY221v9vZXWoJtwzbeIEK81+4qiS7sM=
