language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-item-service
  skip_cleanup: true
  api_key:
    secure: ZRk5jyVUfRmY8Gtw7FT4VW/p98aw230bcltpDa8Cg7ebsAqNVut9JMLBLMpeSXsp4ytUSH1IWYQyef8Xr91EggAslWJhne+QDdVLINIPFA5W2lOd2I0nm98XijnzUZaU5ni/jf2lzsK8XgHVp20XKvhszN/SiftQHLGSG9x8ac8+0tg0aanKp02gfS2WQhiMbkaD+quG8nSxST756zENFVK3q0Q9I2AOhzGKuCS2+TjoIVJo6+zJHUqUTTaaA4RShnYgHmyTaSCFSFact9xP8KnB51uH6alwi+MXYaoW4YPCXIAMfwuhOEtKTpZX3hyvWG2OxLmWWTXVtwnaIqgPHKdF0sh9UEGnvBPKgL9ErJOev0/MjFih+10GXsceQ+pVtvRwwiHXhp9d3sK/dGMJpBNQWsMTjqEX0/fbqTyWLis4b6J+IhY9i235Ugc5/GUma4z16CieAMg6beGFCzwrZ3F/V0LuSkBu2mRpN5bILKV47WyaUb5lgBBlj6VSgI2gzR25bB+MAkJ9fs5f0tNqXnBMRFka9xyGSiA/OhA3E398DQjPOjO74dZDCtIooGtTlRRrEqQpSswEGK1AJoAKUPJUxsLjfWlVgAcCLRsuHd+cDtQMLp4h16xEXn2jt00A7rfpyq6AJbRn8Gc6C+U0jOMgtNzACqs38jKlzLawAuc=
