language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-item-service
  skip_cleanup: true
  api_key:
    secure: xYoXqFlWlkaIrqveRtQWBtgWpgKoBjOG5ntkVCSA6DNUmSovre0ndeO5L3SJUxtlsUB1TPkXC/nWwBZAYaBMjxENKchdII/N7R3v+HojTZ6Os0cMT3TLri5X0NPuTg/OtMyQJyz75NDEiwHBMs5jvJEy9tpfe8JR2rEEtr9rnohzbsadU00RsA7zkYIFzTHzQqxeFGKiU52jBU6kM2kc1e8utErC7RF7kTl+QQmeabJfn6cq0qqH6OHnzLnXXw+NM8WqOY1Bwc66Qm7+N3bXfR1tWZ4MQmgTt9G2nCTlTGI5ppb6aT8IYcxkjLydxAbn40BV57aOeIVJhsEMNkHPJzxYB8BO0FYS8bqiP4pY9eMPFCkzy7bD+/3ZGaJjuzbLd1WgC0HvaCJl/9KszT9kWZYmjaVpL72BRhWHAelobjABYeCrBb+8kQNulgZLQlZdurN0KV9QZCstSqJyFgax8U3NJL0BR4eDvjosP4AxtN7p+JXgZlbryijVWSOTDCLxXpAOybJ+RscjqMvU3+Bkby/5B/sPQGyP5sdv63Dne4wih3wZ+zUsXeMekNMYWrA9yhpGLX5COJhcQbjwJbwalwluNep4C+Ec/fQWrFF4AcJRJIfpdculmztSlm0pyTkdaEK5Yvk11e+39gsF+/kskGcAyjsklFKgFIN+TKBfs3A=
