language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-item-service
  skip_cleanup: true
  api_key:
    secure: 0bu2LjDmUOelZeIO0Ajx+FhphkCSQ11UhoNKg4MVBpleDJT4/6aT91J/EqP4rGrqJA6SJDZ+5Hm/tIRyrGx7ZFSTtNA/mnVmnzizkWFoS5oa5+PuZGqfNQONZyjkvtIhFy6paBGOkFPqvLZc/HxJbFQ7JcY5NhdjVxI5ft98Uo+XdAO2qcXM6+Zb+uli1nmONxSIFlPwbXvDUVn+a8G0l2LCChkEwueSPGEDcdVWh0w15shoaTAe2AjhOFFqe6XzNphgW4qnGejYt1bDJKz/e05iV2BsEG3IBsgZfA/cIKYrxyKaNb0td3R5ctEI7fb6utSCzibc0ZKCIiT6cDEpfUt2CL7pjbjqFKQ8V5IjFViUDRcACHeo3SwvU+SQxX79YZvsPukpVte3d8R/SFNg493kkMfmiaYQ43b7MTqG8wQZifiZtXl6DHzkLPWJQt9atNcewdcLnv+6O4ulCEjddJ4OuC5lcEWXBHQXz8EKQv1zSdyZnaSytIlnu6zP7A9O19JCAHReq08NwPXzPXVWrRPQ5iwP6eLejowUnHv//HYAxPjctyMXb6z993GXkmErsQGYd+Dq8BceAZK8Qfy7uHuacwsSflo7MIgI8YyalP3yi4gHTTMibdxUp42k0LgYN9OOgsuA254Bux/YuNRx9CFIbHGV2BFEcq4Tsyl9FgY=
